export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
// export const PRODUCT_LOADING_TYPE = 'PRODUCT_LOADING_TYPE'