export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';
export const PRODUCT_COMMENTS = 'PRODUCT_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
// export const PRODUCT_LOADING_TYPE = 'PRODUCT_LOADING_TYPE'
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_AUTH = 'LOGIN_AUTH';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
export const CHECK_USER = 'CHECK_USER';
export const CHECK_AUTH = 'CHECK_AUTH';